import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import React, { ReactNode } from 'react'
import AntdProvider from '@/providers/AntdProvider'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AntdProvider>{children}</AntdProvider>
			</body>
		</html>
	)
}
