import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import React, { ReactNode } from 'react'
import AntdProvider from '@/providers/AntdProvider'
import { StoreProvider } from '@/providers/ReduxProvider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="en">
		<body className={inter.className}>
		<StoreProvider>
			<AntdProvider>{children}</AntdProvider>
			<Toaster />
		</StoreProvider>
		</body>
		</html>
	)
}
